In [26]:
# one hot encoding
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


In [27]:
# read the data from keyboard
data = input("Enter the data: ")
data = str(data)


In [28]:
print("Data: ", data)

Data:  ali va a la centrale ali


In [29]:
# tokenize the data
tokens = word_tokenize(data)
print("Tokens: ", tokens)

Tokens:  ['ali', 'va', 'a', 'la', 'centrale', 'ali']


In [30]:
#create indexed dictionary with data and without duplicates
indexed_dict = dict(enumerate(set(tokens)))
# order dictionary alphabetically
indexed_dict = dict(sorted(indexed_dict.items(), key=lambda x: x[1]))
print("Indexed Dictionary: ", indexed_dict)

Indexed Dictionary:  {1: 'a', 3: 'ali', 0: 'centrale', 4: 'la', 2: 'va'}


In [31]:
# create the one hot encoding matrix with zeros
one_hot_matrix = np.zeros((len(indexed_dict), len(tokens)))
for i, word in enumerate(tokens):
    one_hot_matrix[list(indexed_dict.values()).index(word), i] = 1

print(one_hot_matrix)


[[0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


In [32]:
# extract the one hot encodeing array of tokens
def one_hot_encoding(data):
    tokens = word_tokenize(data)
    indexed_dict = dict(enumerate(set(tokens)))
    indexed_dict = dict(sorted(indexed_dict.items(), key=lambda x: x[1]))
    one_hot_matrix = np.zeros((len(indexed_dict), len(tokens)))
    for i, word in enumerate(tokens):
        one_hot_matrix[list(indexed_dict.values()).index(word), i] = 1
    one_hot_dict = dict(zip(indexed_dict.values(), one_hot_matrix))
    # for key, value in one_hot_dict.items():
    #     print(key, value)
    return one_hot_dict


In [33]:
one_hot_encoding(data)

{'a': array([0., 0., 1., 0., 0., 0.]),
 'ali': array([1., 0., 0., 0., 0., 1.]),
 'centrale': array([0., 0., 0., 0., 1., 0.]),
 'la': array([0., 0., 0., 1., 0., 0.]),
 'va': array([0., 1., 0., 0., 0., 0.])}